<?php

//
//English language file for tplLeagueStats 1.0
//by Andrew Lincoln (www.saints-alive.co.uk)
//

//
//Shared
//
$lng_moveto = 'Move to';
$lng_change_season = 'Change season';
$lng_change_language = 'Change language';
$lng_none = 'None';

//
//Dropdowns
//
$lng_all = 'All';
$lng_show_all = 'Show all';
$lng_show_own_only = 'Own matches only';
$lng_do_not_show = 'Do not show';
$lng_headtohead_drop = 'Head-to-head';
$lng_season_statistics_drop = 'Season statistics';
$lng_tables_drop = 'Tables';
$lng_simple = 'Simple';
$lng_traditional = 'Traditional';
$lng_mathematical = 'Mathematical';
$lng_recent_form = 'Recent form';

//
//index.php
//
$lng_match_calendar = 'Fixture calendar';
$lng_table = 'Table';
$lng_last_update = 'Last updated';
$lng_position_short = 'Pos';
$lng_team = 'Team';
$lng_played_short = 'Pld';
$lng_wins_short = 'W';
$lng_draws_short = 'D';
$lng_loses_short = 'L';
$lng_goals_for_short = 'F';
$lng_goals_against_short = 'A';
$lng_points_short = 'Pts';
$lng_overall = 'Overall';
$lng_home = 'Home';
$lng_away = 'Away';
$lng_total_wins_short = 'TW';
$lng_total_draws_short = 'TD';
$lng_total_loses_short = 'TL';
$lng_total_goals_for_short = 'TF';
$lng_total_goals_against_short = 'TA';
$lng_average_points_short = 'Avg. Pts';
$lng_win_percent = 'Win %';
$lng_draw_percent = 'Draw %';
$lng_loss_percent = 'Loss %';
$lng_average_goals_for_short = 'Avg. For';
$lng_average_goals_against_short = 'Avg. Agst.';
$lng_average_goal_difference_short = 'Avg. GDiff.';
$lng_no_matches_yet = 'No matches yet.';

//
//headtohead.php
//
$lng_home_team = 'Home team';
$lng_away_team = 'Away team';
$lng_vs = 'vs.';
$lng_w_d_l = 'W-D-L';
$lng_goal_difference = 'Goal difference';
$lng_headtohead = 'Head-to-head';
$lng_latest_headtohead_matches = 'Latest head-to-head matches (max 5)';
$lng_overall_match_statistics = 'Overall match statistics';
$lng_points_earned = 'Points';
$lng_matches_played_overall = 'Matches played overall';
$lng_matches_won_overall = 'Matches won overall';
$lng_matches_drawn_overall = 'Matches drawn overall';
$lng_matches_lost_overall = 'Matches lost overall';
$lng_home_matches_played_overall = 'Home matches played overall';
$lng_home_matches_won_overall = 'Home matches won overall';
$lng_home_matches_drawn_overall = 'Home matches drawn overall';
$lng_home_matches_lost_overall = 'Home matches lost overall';
$lng_away_matches_played_overall = 'Away matches played overall';
$lng_away_matches_won_overall = 'Away matches won overall';
$lng_away_matches_drawn_overall = 'Away matches drawn overall';
$lng_away_matches_lost_overall = 'Away matches lost overall';
$lng_goal_difference_overall = 'Goal difference overall';
$lng_goal_difference_in_home = 'Goal difference home';
$lng_goal_difference_in_away = 'Goal difference away';
$lng_biggest_home_win = 'Biggest home win';
$lng_biggest_home_lost = 'Biggest home loss';
$lng_highest_aggregate_in_home = 'Highest aggregate score home';
$lng_biggest_away_win = 'Biggest away win';
$lng_biggest_away_lost = 'Biggest away loss';
$lng_highest_aggregate_in_away = 'Highest aggregate score away';

//
//season.php
//
$lng_season_statistics = 'Season statistics';
$lng_season_filter = 'Season filter';
$lng_matches_played = 'Matches played';
$lng_home_wins = 'Home wins';
$lng_away_wins = 'Away wins';
$lng_draws = 'Draws';
$lng_total_goals_scored = 'Total goals scored';
$lng_home_team_goals = 'Home team goals';
$lng_away_team_goals = 'Away team goals';
$lng_highest_aggregate_score = 'Highest aggregate score';
$lng_average = 'Average';
$lng_per_match = 'per match';

?>