<?php 

// 
//Finnish language file for tplLeagueStats 1.0 
//by Kimmo Helle (www.unitedweb.net)
// 

// 
//Shared 
// 
$lng_moveto = 'Siirry'; 
$lng_change_season = 'Vaihda kautta'; 
$lng_change_language = 'Vaihda kieltä'; 
$lng_none = 'Ei yhtään'; 

// 
//Dropdowns 
// 
$lng_all = 'Kaikki'; 
$lng_show_all = 'Näytä kaikki ottelut'; 
$lng_show_own_only = 'Vain omat ottelut'; 
$lng_do_not_show = 'Älä näytä'; 
$lng_headtohead_drop = 'Vastakkain'; 
$lng_season_statistics_drop = 'Kausitilastot'; 
$lng_tables_drop = 'Taulukot'; 
$lng_simple = 'Yksinkertainen'; 
$lng_traditional = 'Perinteinen'; 
$lng_mathematical = 'Matemaattinen'; 
$lng_recent_form = 'Kuntopuntari'; 

// 
//index.php 
// 
$lng_match_calendar = 'Otteluohjelma'; 
$lng_table = 'Taulukko'; 
$lng_last_update = 'Viimeksi päivitetty'; 
$lng_position_short = 'Sij.'; 
$lng_team = 'Joukkue'; 
$lng_played_short = 'Ott'; 
$lng_wins_short = 'V'; 
$lng_draws_short = 'T'; 
$lng_loses_short = 'H'; 
$lng_goals_for_short = 'TM'; 
$lng_goals_against_short = 'PM'; 
$lng_points_short = 'Pis'; 
$lng_overall = 'Yhteensä'; 
$lng_home = 'Kotona'; 
$lng_away = 'Vieraissa'; 
$lng_total_wins_short = 'V'; 
$lng_total_draws_short = 'T'; 
$lng_total_loses_short = 'H'; 
$lng_total_goals_for_short = 'TM'; 
$lng_total_goals_against_short = 'PM'; 
$lng_average_points_short = 'Ka.Pis'; 
$lng_win_percent = 'Voitto %'; 
$lng_draw_percent = 'Tasapeli %'; 
$lng_loss_percent = 'Tappio %'; 
$lng_average_goals_for_short = 'Ka.TM'; 
$lng_average_goals_against_short = 'Ka.PM'; 
$lng_average_goal_difference_short = 'Ka.MEro.'; 
$lng_no_matches_yet = 'Ei vielä otteluita.'; 

// 
//headtohead.php 
// 
$lng_home_team = 'Kotijoukkue'; 
$lng_away_team = 'Vierasjoukkue'; 
$lng_vs = 'vs.'; 
$lng_w_d_l = 'V-T-H'; 
$lng_goal_difference = 'Maaliero'; 
$lng_headtohead = 'Vastakkain'; 
$lng_latest_headtohead_matches = 'Viimeisimmät kohtaamiset (max. 5)'; 
$lng_overall_match_statistics = 'Kausitilastot'; 
$lng_points_earned = 'Pisteet'; 
$lng_matches_played_overall = 'Pelattuja otteluita'; 
$lng_matches_won_overall = 'Voitot yhteensä'; 
$lng_matches_drawn_overall = 'Tasapelit yhteensä'; 
$lng_matches_lost_overall = 'Tappiot yhteensä'; 
$lng_home_matches_played_overall = 'Pelattuja kotiotteluita'; 
$lng_home_matches_won_overall = 'Kotivoitot'; 
$lng_home_matches_drawn_overall = 'Kotitasapelit'; 
$lng_home_matches_lost_overall = 'Kotitappiot'; 
$lng_away_matches_played_overall = 'Pelattuja vierasotteluita'; 
$lng_away_matches_won_overall = 'Vierasvoitot'; 
$lng_away_matches_drawn_overall = 'Vierastasapelit'; 
$lng_away_matches_lost_overall = 'Vierastappiot'; 
$lng_goal_difference_overall = 'Maalisuhde kokonaisuudessaan'; 
$lng_goal_difference_in_home = 'Maalisuhde kotona'; 
$lng_goal_difference_in_away = 'Maalisuhde vieraissa'; 
$lng_biggest_home_win = 'Suurin kotivoitto'; 
$lng_biggest_home_lost = 'Suurin kotitappio'; 
$lng_highest_aggregate_in_home = 'Suurin maalimäärä kotona'; 
$lng_biggest_away_win = 'Suurin vierasvoitto'; 
$lng_biggest_away_lost = 'Suurin vierastappio'; 
$lng_highest_aggregate_in_away = 'Suurin maalimäärä vieraissa'; 

// 
//season.php 
// 
$lng_season_statistics = 'Kausitilastot'; 
$lng_season_filter = 'Kausi filtteri'; 
$lng_matches_played = 'Pelattuja otteluita'; 
$lng_home_wins = 'Kotivoitot'; 
$lng_away_wins = 'Vierasvoitot'; 
$lng_draws = 'Tasapelit'; 
$lng_total_goals_scored = 'Maaleja yhteensä'; 
$lng_home_team_goals = 'Kotijoukkueen maaleja'; 
$lng_away_team_goals = 'Vierasjoukkueen maaleja'; 
$lng_highest_aggregate_score = 'Eniten maaleja ottelussa'; 
$lng_average = 'Keskimäärin'; 
$lng_per_match = 'ottelua kohden'; 

?>